const header=document.querySelector('#header');const menuButton=document.querySelector('.menu-toggle');const mobileMenu=document.querySelector('.mobile-nav');
const closeMenu=()=>{menuButton.setAttribute('aria-expanded','false');mobileMenu.classList.remove('open');document.body.classList.remove('menu-open')};
menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));mobileMenu.classList.toggle('open',!open);document.body.classList.toggle('menu-open',!open)});mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
const heroSection=document.querySelector('.hero');const headerObserver=new IntersectionObserver(([entry])=>header.classList.toggle('scrolled',!entry.isIntersecting),{rootMargin:'-40px 0px 0px'});headerObserver.observe(heroSection);
const revealElements=[...document.querySelectorAll('.reveal')];
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -6%'});
revealElements.forEach(el=>{if(!reduceMotion&&el.getBoundingClientRect().top>window.innerHeight*.78)el.classList.add('motion-ready');observer.observe(el)});
const today=new Date().getDay();document.querySelector(`[data-day="${today}"]`)?.classList.add('today');
const filterButtons=document.querySelectorAll('.gallery-filters button');const galleryItems=document.querySelectorAll('.gallery-item');filterButtons.forEach(button=>button.addEventListener('click',()=>{filterButtons.forEach(b=>b.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;galleryItems.forEach(item=>item.classList.toggle('hidden',filter!=='all'&&item.dataset.category!==filter))}));
const lightbox=document.querySelector('#lightbox');const lightboxImage=lightbox.querySelector('.lightbox-image');galleryItems.forEach(item=>item.addEventListener('click',()=>{const source=item.querySelector('img');lightboxImage.className='lightbox-image';lightboxImage.innerHTML=`<img src="${source.src}" alt="${item.getAttribute('aria-label').replace('Avaa kuva: ','')}">`;lightbox.showModal()}));lightbox.querySelector('.lightbox-close').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});
const aboutSlider=document.querySelector('.about-slider');if(aboutSlider){const main=aboutSlider.querySelector('.about-slide-main');const thumbs=[...aboutSlider.querySelectorAll('.about-thumbs button')];let current=0;const show=index=>{current=(index+thumbs.length)%thumbs.length;const thumb=thumbs[current];main.src=thumb.dataset.src;main.alt=thumb.dataset.alt;thumbs.forEach((button,i)=>button.classList.toggle('active',i===current))};thumbs.forEach((button,i)=>button.addEventListener('click',()=>show(i)));aboutSlider.querySelector('.about-slide-prev').addEventListener('click',()=>show(current-1));aboutSlider.querySelector('.about-slide-next').addEventListener('click',()=>show(current+1))}
const form=document.querySelector('#contact-form');form.addEventListener('submit',event=>{event.preventDefault();let valid=true;const required=form.querySelectorAll('[required]');required.forEach(input=>{const field=input.closest('.field');const error=field.querySelector('.error');let message='';if(!input.value.trim())message='Täytä tämä kenttä.';else if(input.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.value))message='Tarkista sähköpostiosoite.';field.classList.toggle('invalid',!!message);error.textContent=message;if(message)valid=false});if(!valid){form.querySelector('.invalid input, .invalid textarea')?.focus();return}const data=new FormData(form);const subject=encodeURIComponent('Yhteydenotto verkkosivulta: '+data.get('name'));const body=encodeURIComponent(`Nimi: ${data.get('name')}\nPuhelin: ${data.get('phone')||'-'}\nSähköposti: ${data.get('email')}\n\nViesti:\n${data.get('message')}`);document.querySelector('#form-note').textContent='Sähköpostiohjelma avataan viestiä varten…';window.location.href=`mailto:info@jessicamaibeauty.fi?subject=${subject}&body=${body}`});form.querySelectorAll('input,textarea').forEach(input=>input.addEventListener('input',()=>{input.closest('.field').classList.remove('invalid');input.closest('.field').querySelector('.error').textContent=''}));
